### ISSUE TITLE
Webhook for bot

### ISSUE THREAD

**Issue by rapha18th** [melvinalmonte/covid-bot#1]
Hi there! how did you build the webhook for tje dialogflow to connect to the Covid-19 API, if you did it another way can you please let me know.

**Comment by melvinalmonte** [comment]
Hello!, 

I used DialogFlow's fulfillment hook which is just a GCP function to connect to the API. The function itself was written in JS and it was relatively straight forward If you'd like to see it I can add it to the repo under the scripts directory. Let me know if you have any questions.

**Comment by rapha18th** [comment]
Thank you will check out the script
